# Generated by Django 3.2.12 on 2022-04-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_examform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examform',
            new_name='ExamModel',
        ),
    ]
